# NumPy Library
**NumPy** is a Linear Algebra Library for Python. This is one of the most important libraries for Data Analytics with Python because almost all the libraries on the PyData Ecosystem rely on it as one of their building blocks.
NumPy is also very fast, as it has bidings to C libraries that deals directly with the operating system.

In this document I will cover some of the most important aspects of NumPy like:
* Vectors
* Arrays
* Matrices

## Using NumPy
First you will have to import the library into the kernel.

In [37]:
import numpy as np

## NumPy Arrays
NumPy arrays come in two flavors:
1. Vectors
2. Matrices
*Vectors* are 1-d arrays while *Matrices* are 2-d arrays 

### Creating Vectors and Arrays

In [38]:
myVector = np.array([1,2,3])
myVector

array([1, 2, 3])

In [39]:
myMatrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
myMatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## NumPy Built-in Methods
NumPy has a lot of ways to generate arrays using built-in methods

### arange
Return evenly spaced values within an interval

In [40]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.arange(0,11,2) #the third argument represents an interval

array([ 0,  2,  4,  6,  8, 10])

### zeroes and ones
Return arrays of zeros or ones

In [42]:
np.zeros(3)

array([0., 0., 0.])

In [43]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [44]:
np.ones(3)

array([1., 1., 1.])

In [45]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval

In [46]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [47]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## Random Number Generator
NumPy has a lot of ways to create random number arrays
### rand
Create an array of random numbers from a uniform distribution over 0 and 1

In [48]:
np.random.rand(5)

array([0.08950694, 0.13115603, 0.38930111, 0.23953405, 0.9564699 ])

### randn
Return a sample from a "standard Normal distribution". Unlike rand which is uniform

In [49]:
np.random.randn(5)

array([-1.49895976,  1.16498077,  0.41459541, -0.20378298,  0.29948844])

In [50]:
np.random.randn(5,5)

array([[-1.29131002, -1.16972433,  2.23084165, -0.34747838, -1.56691125],
       [-0.37842096,  2.59633478,  1.41063372, -0.31315703,  1.00488373],
       [-0.83127817, -0.07812948, -0.37315997, -0.54336845, -0.55379009],
       [-0.85282684,  1.33088762,  0.44479001, -0.5904954 , -0.60026376],
       [ 1.67319293, -0.72293963,  0.73097049, -0.21798977, -0.65103867]])

### randint
Return random integers from low (inclusive) to high (exclusive).

In [51]:
np.random.randint(1,100)

25

In [52]:
np.random.randint(1,50,10)

array([18, 26, 27, 35, 37, 28, 18, 17, 42, 26])

## Array Attributes and Methods
### reshape

In [53]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [54]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin
these are useful methods for finding maximum or minimum values, or to find thier index locations.

In [55]:
randarr = np.random.randint(0,50,10)
randarr

array([38, 30, 49, 26, 39, 21, 34, 15, 24, 41])

In [56]:
randarr.max()

49

In [57]:
randarr.min()

15

In [58]:
randarr.argmax()

2

In [59]:
randarr.argmin()

7

### dtype
Returns the datatype of the array elements.
dtype is an attribute and NOT a method, as such the parenteses after the name is not necessary

In [60]:
arr.dtype

dtype('int32')